include:
  - project: 'hog/Hog'
    file: '/hog.yml'
    ref: 'Hog2026.1-1'  

variables:
        VIVADO_VERSION: 2019.2
        HOG_DEVELOP_BRANCH: 'develop'

## Generic FW build rule ###
.firmware_build:
        image: gitlab-registry.cern.ch/cce/docker_build/vivado:2019.2
        extends: .generate_project
        variables:
                extends: .vars
                PROJECT_NAME: $CI_JOB_NAME
                HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
        artifacts:
                when: always
                name: bitfiles
                paths:
                        - bin
                        - bit
                expire_in: never
        hooks:
                pre_get_sources_script:
                        - yum update -y
                        - yum install wget which zlib-devel perl-devel gettext -y
                        - wget https://github.com/git/git/archive/v2.7.2.tar.gz -O /tmp/git.tar.gz
                        - cd /tmp && tar -zxf git.tar.gz
                        - cd /tmp/git-2.7.2
                        - make configure
                        - ./configure
                        - make install
                        - git --version
                        - echo "=== Pre Get Sources Script Completed ==="
        before_script:
                - echo "=== Before Script ==="
                - git --version


#### FW Builds ###
odmb5_ucsb_dev:
        extends: .firmware_build
        variables:
                extends: .vars
                PROJECT_NAME: $CI_JOB_NAME
                HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
                VIVADO_VERSION: $VIVADO_VERSION
odmb7_ucsb_dev:
        extends: .firmware_build
        variables:
                extends: .vars
                PROJECT_NAME: $CI_JOB_NAME
                HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
                VIVADO_VERSION: $VIVADO_VERSION
