# Run by source group_ports.tcl
create_hw_probe -m probe0[22]       alct_mgt_rxready_s                        [get_hw_ilas hw_ila_6]
create_hw_probe -m probe0[21]       alct_mgt_txready_s                        [get_hw_ilas hw_ila_6]
create_hw_probe -m probe0[20:13]    alct_gbtbank_rxbitslip_rst_cnt_s[7:0]     [get_hw_ilas hw_ila_6]
create_hw_probe -m probe0[8]        alct_RX_ENCODING_SEL_i                    [get_hw_ilas hw_ila_6]
create_hw_probe -m probe0[7]        alct_gbt_rxreset_s                        [get_hw_ilas hw_ila_6]            
create_hw_probe -m probe0[6]        alct_mgt_rxreset_s                        [get_hw_ilas hw_ila_6]            
create_hw_probe -m probe0[5]        alct_TX_ENCODING_SEL_i                    [get_hw_ilas hw_ila_6]            
create_hw_probe -m probe0[4]        alct_gbt_txreset_s                        [get_hw_ilas hw_ila_6]            
create_hw_probe -m probe0[3]        alct_mgt_txreset_s                        [get_hw_ilas hw_ila_6]            
create_hw_probe -m probe0[2]        alct_GBTBANK_MANUAL_RESET_RX_I            [get_hw_ilas hw_ila_6]            
create_hw_probe -m probe0[1]        alct_GBTBANK_MANUAL_RESET_TX_I            [get_hw_ilas hw_ila_6]
create_hw_probe -m probe0[0]        alct_GBTBANK_GENERAL_RESET_I              [get_hw_ilas hw_ila_6]

create_hw_probe -m probe0[205]      alct_gbt_rxclkenLogic_s                   [get_hw_ilas hw_ila_7]
create_hw_probe -m probe0[203:120]  alct_gbtbank_rx_bitmodified_flag_s[83:0]  [get_hw_ilas hw_ila_7]            
create_hw_probe -m probe0[119]      alct_gbtbank_rx_errordetected_s           [get_hw_ilas hw_ila_7]            
create_hw_probe -m probe0[118]      alct_gbt_rxready_s                        [get_hw_ilas hw_ila_7]            
create_hw_probe -m probe0[117]      alct_mgt_headerflag_s                     [get_hw_ilas hw_ila_7]            
create_hw_probe -m probe0[116]      alct_gbtbank_rx_isdata_sel_s              [get_hw_ilas hw_ila_7]            
create_hw_probe -m probe0[115:84]   alct_wb_rxdata_s[31:0]                    [get_hw_ilas hw_ila_7]
create_hw_probe -m probe0[83:0]     alct_gbt_rxdata_s[83:0]                   [get_hw_ilas hw_ila_7]

create_hw_probe -m probe0[117]      alct_gbt_txclken_s                        [get_hw_ilas hw_ila_8]            
create_hw_probe -m probe0[116]      alct_GBTBANK_TX_ISDATA_SEL_I              [get_hw_ilas hw_ila_8]            
create_hw_probe -m probe0[115:84]   alct_wb_txdata_s[31:0]                    [get_hw_ilas hw_ila_8]
create_hw_probe -m probe0[83:0]     alct_gbt_txdata_s[83:0]                   [get_hw_ilas hw_ila_8]
