# Run by source group_ports.tcl
create_hw_probe -m probe0[22]       fed_mgt_rxready_s                        [get_hw_ilas hw_ila_3]
create_hw_probe -m probe0[21]       fed_mgt_txready_s                        [get_hw_ilas hw_ila_3]
create_hw_probe -m probe0[20:13]    fed_gbtbank_rxbitslip_rst_cnt_s[7:0]     [get_hw_ilas hw_ila_3]
create_hw_probe -m probe0[8]        fed_RX_ENCODING_SEL_i                    [get_hw_ilas hw_ila_3]
create_hw_probe -m probe0[7]        fed_gbt_rxreset_s                        [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[6]        fed_mgt_rxreset_s                        [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[5]        fed_TX_ENCODING_SEL_i                    [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[4]        fed_gbt_txreset_s                        [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[3]        fed_mgt_txreset_s                        [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[2]        fed_GBTBANK_MANUAL_RESET_RX_I            [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[1]        fed_GBTBANK_MANUAL_RESET_TX_I            [get_hw_ilas hw_ila_3]
create_hw_probe -m probe0[0]        fed_GBTBANK_GENERAL_RESET_I              [get_hw_ilas hw_ila_3]

create_hw_probe -m probe0[205]      fed_gbt_rxclkenLogic_s                   [get_hw_ilas hw_ila_4]
create_hw_probe -m probe0[203:120]  fed_gbtbank_rx_bitmodified_flag_s[83:0]  [get_hw_ilas hw_ila_4]            
create_hw_probe -m probe0[119]      fed_gbtbank_rx_errordetected_s           [get_hw_ilas hw_ila_4]            
create_hw_probe -m probe0[118]      fed_gbt_rxready_s                        [get_hw_ilas hw_ila_4]            
create_hw_probe -m probe0[117]      fed_mgt_headerflag_s                     [get_hw_ilas hw_ila_4]            
create_hw_probe -m probe0[116]      fed_gbtbank_rx_isdata_sel_s              [get_hw_ilas hw_ila_4]            
create_hw_probe -m probe0[115:84]   fed_wb_rxdata_s[31:0]                    [get_hw_ilas hw_ila_4]
create_hw_probe -m probe0[83:0]     fed_gbt_rxdata_s[83:0]                   [get_hw_ilas hw_ila_4]

create_hw_probe -m probe0[117]      fed_gbt_txclken_s                        [get_hw_ilas hw_ila_5]            
create_hw_probe -m probe0[116]      fed_GBTBANK_TX_ISDATA_SEL_I              [get_hw_ilas hw_ila_5]            
create_hw_probe -m probe0[115:84]   fed_wb_txdata_s[31:0]                    [get_hw_ilas hw_ila_5]
create_hw_probe -m probe0[83:0]     fed_gbt_txdata_s[83:0]                   [get_hw_ilas hw_ila_5]
